version: '3'

services:
  apiusers:
    image: "apiusers:v1"
    ports:
      - 8082:8082
    environment:
      DB_URL: jdbc:postgresql://database:5432/db_user
    restart: always
  apistocks:
    image: "apistocks:v1"
    ports:
      - 8083:8083
    environment:
      DB_URL: jdbc:postgresql://database:5432/db_stock
    restart: always
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: solinftec
      POSTGRES_DB: postgres
    volumes:
      - /var/usr/lib/postgresql/14/main
    restart: always
